#pragma once

using namespace ATL;

template <class T>
class CProxy_IContext2DEvents : public IConnectionPointImpl<T, &__uuidof( _IContext2DEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
