#pragma once

using namespace ATL;

template <class T>
class CProxy_IContextWebGLEvents : public IConnectionPointImpl<T, &__uuidof( _IContextWebGLEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
